[package]
name = "tennis_rounds"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.6"
bevy_input = { git = "https://github.com/SecretPocketCat/bevy_input", features = [
    "multiplayer",
] }
bevy_extensions = { git = "https://github.com/SecretPocketCat/bevy_extensions" }
bevy_time = { git = "https://github.com/SecretPocketCat/bevy_time" }
# serde = { version = "1.0.130", features = ["derive"] }
rand = "0.8.5"
bevy_tweening = "*"
bevy-inspector-egui = { version = "0.8.2" }
heron = { version = "2.0.1", features = ["2d"] }
# heron = { version = "2.0.1", features = ["2d", "debug-2d"] }
